apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: daskautoscalers.kubernetes.dask.org
spec:
  group: kubernetes.dask.org
  names:
    kind: DaskAutoscaler
    plural: daskautoscalers
    shortNames:
    - as
    singular: daskautoscaler
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              cluster:
                description: Name of the cluster to scale
                type: string
              maximum:
                description: Maximum number of workers
                type: integer
              minimum:
                description: Minimum number of workers
                type: integer
            type: object
          status:
            type: object
        type: object
    served: true
    storage: true
