apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: daskautoscalers.kubernetes.dask.org
spec:
  scope: Namespaced
  group: kubernetes.dask.org
  names:
    kind: DaskAutoscaler
    plural: daskautoscalers
    singular: daskautoscaler
    shortNames:
      - as
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                minimum:
                  type: integer
                  description: Minimum number of workers
                maximum:
                  type: integer
                  description: Maximum number of workers
            status:
              type: object